// Static picks data (generated by scripts/freeze-data.mjs)
let staticPicks = null;

try {
  // This will be available after running the freeze-data script
  const module = await import('../data/picks.json');
  staticPicks = module.default;
} catch (e) {
  // picks.json doesn't exist yet — that's fine during development
}

// Group display name (only Friends & Family now)
export const GROUP_NAME = 'Friends & Family';

/**
 * Returns participant picks from the static JSON file.
 * Falls back to fetching from Google Sheets if static data isn't available.
 */
export async function fetchPicks() {
  if (staticPicks && staticPicks.length > 0) {
    return staticPicks;
  }

  // Fallback: fetch from Google Sheets (for development before freezing)
  const Papa = (await import('papaparse')).default;
  const sheetUrl =
    'https://docs.google.com/spreadsheets/d/e/2PACX-1vTI03o7UvWy2x7Mg55mjOO9Gsn3MiQRoh5ARc28xdIfDkxGvFy57PfweWp1fg085OaFigO9Yz8ykyyc/pub?output=csv';

  const response = await fetch(`${sheetUrl}&_cb=${Date.now()}`, {
    cache: 'no-store',
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch sheet: ${response.status}`);
  }

  const csvText = await response.text();

  return new Promise((resolve, reject) => {
    Papa.parse(csvText, {
      header: true,
      skipEmptyLines: true,
      complete: (results) => {
        const picks = results.data.map((row, index) => {
          const nameKey =
            Object.keys(row).find(
              (key) =>
                key.toLowerCase().includes('name') &&
                !key.toLowerCase().includes('what')
            ) || Object.keys(row)[1];

          return {
            id: `ff-${index}`,
            name: row[nameKey] || `Player ${index + 1}`,
            timestamp: row['Timestamp'] || row[Object.keys(row)[0]],
            picks: row,
          };
        });
        resolve(picks);
      },
      error: (error) => {
        reject(new Error(`CSV parse error: ${error.message}`));
      },
    });
  });
}
